### ISSUE TITLE
The template need to update

### ISSUE THREAD

**Issue by ghost** [telegram-bot-rb/rails_template#1]
I tried to install this template, but these gems versions are not up to date. the puma is 3.6.2 and can't compile. (see https://github.com/puma/puma/issues/1136 and https://github.com/puma/puma/issues/1195)
But I do a fresh install of rails 5.1, the puma is 3.8.2 and install succeeded.

**Comment by printercu** [comment]
Hi! Just tried command from The top of readme and everything was fine.

There could be different reasons why you could got a error:

- you had some old versions of gems installed, and `bundle install` used them along with new rails, because of not sufficient restrictions in gemspecs.
- you had no puma installed, and it tried to install new version, which caused error.
- this may depend on ruby version you were using while `rails new`, as different versions have different gemsets.

You can see that https://github.com/telegram-bot-rb/rails_template/blob/master/rails_template.rb has no any of gem version specified, so it can not be updated.

**Comment by ghost** [comment]
@printercu I run `bundle update` and all gems was updated.
