### ISSUE TITLE
How can I just view my chat updates?

### ISSUE THREAD

**Issue by edencoded** [telegram-bot-rb/rails_template#4]
If you want to just view chat updates on one of your web pages(just like getUpdates method), how would you go about doing so?
I set my webhook url to go to my webhooks controller.
I believe I need to `post webhooks/webhook` in routes
and my controller has this code `def webhook
  	params['webhook']
  end`
and my view has `<% @webhooks %>`

I'm new to the rails MVC so I'm not sure where/how I should make my app show me my updates. Thanks in advance!

**Comment by printercu** [comment]
Hi! MVC does not apply to this: it's architecture to handle single request, but you have web-page requests (lets say `GET /chats/:id` to show specific chat) and also asynchronous updates from telegram for all chats your bot is in. This may be webhooks to the single endpoint (`POST /telegram/:bot_token`) or updates from poller. Poller itself may work without web server, in separate process.

So we got: you want to show updates for each chat on separate pages, bot receives updates for __all__ his chats in single place (maybe in separate process). Note, that if you want to handle just single chat, you need to restrict it somehow, because everybody can add your bot to any chat and you'll receive updates from this chats too.

I see 2 approaches:

- If you want to show realtime updates, use ActionCable (see rails guides for howto). You create channels for each chat, and bot publishes updates to specific channel based on `chat_id`. You need storage here just to map `telegram_chat_id => your_chat_id`. But this way user will see only updates appeared after pageload.

- If you want to show chat history, bot have to store all messages and then you just render them in `GET /chats/:id`.

To have realtime updates with history, combine both methods.

**Comment by edencoded** [comment]
It seems like ActionCable is difficult to use once it's time to push to production (having to use 2 servers etc.) It seems like there should be a much easier way to save the chats to my database. Once I have chats saved there, I know how I'd be able to view them. When I want to implement the realtime updates, I guess I could just use AJAX. I guess this would be a better question to ask:

Once I have the webhook set to send data to my Webhooks controller, how can I save the incoming information to my database? 

(I just want to make sure my application is receiving the updates)

**Comment by printercu** [comment]
If you don't need to send something back to telegram or extract commands from messages, you may use ActionController without telegram-bot gem:

```ruby
# routes.rb
post '/telegram/here_is_some_secret_or_token', to: 'telegram_webhooks#update'

# telegram_webhooks_controller.rb
class TelegramWebhooksController < ApplicationController
  def update
    your_update_is_here = request.request_parameters
    save_somehow(your_update_is_here)
  end
end
```

**Comment by edencoded** [comment]
Thank you :)

**Comment by edencoded** [comment]
Any idea on why I'm getting the "No route matches [GET] "/telegram/[mytoken]"? I don't have to have a GET do I?

**Comment by printercu** [comment]
User-Agent header of this requests may help to investigate the case. If you have nginx in front of your rails app, check out access log user - user-agent is already logged. Telegram's webhooks use only POST requests.
